"""The incident, and its timeline."""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    Boolean, DateTime, ForeignKey, Integer, Numeric, String, Text, func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base


class SupportTicket(Base):
    __tablename__ = "support_tickets"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.uuid_generate_v4()
    )
    # Generated by the database, so two concurrent inserts cannot collide.
    ticket_number: Mapped[str] = mapped_column(
        Text, unique=True, server_default=func.next_ticket_number()
    )
    title: Mapped[str] = mapped_column(Text)

    status: Mapped[str] = mapped_column(Text, default="NEW", server_default="NEW")
    priority: Mapped[str | None] = mapped_column(Text, nullable=True)
    severity: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    customer_name: Mapped[str | None] = mapped_column(Text, nullable=True)
    organization: Mapped[str | None] = mapped_column(Text, nullable=True)

    product: Mapped[str | None] = mapped_column(Text, nullable=True)
    product_version: Mapped[str | None] = mapped_column(Text, nullable=True)

    service: Mapped[str | None] = mapped_column(Text, nullable=True)
    component: Mapped[str | None] = mapped_column(Text, nullable=True)
    subcomponent: Mapped[str | None] = mapped_column(Text, nullable=True)

    environment: Mapped[str | None] = mapped_column(Text, nullable=True)
    environment_type: Mapped[str | None] = mapped_column(Text, nullable=True)

    operating_system: Mapped[str | None] = mapped_column(Text, nullable=True)
    cloud_provider: Mapped[str | None] = mapped_column(Text, nullable=True)
    region: Mapped[str | None] = mapped_column(Text, nullable=True)
    datacenter: Mapped[str | None] = mapped_column(Text, nullable=True)
    cluster: Mapped[str | None] = mapped_column(Text, nullable=True)
    node: Mapped[str | None] = mapped_column(Text, nullable=True)

    business_impact: Mapped[str | None] = mapped_column(Text, nullable=True)
    technical_impact: Mapped[str | None] = mapped_column(Text, nullable=True)

    users_affected: Mapped[int | None] = mapped_column(Integer, nullable=True)
    percentage_affected: Mapped[Decimal | None] = mapped_column(Numeric(5, 2), nullable=True)

    problem_summary: Mapped[str | None] = mapped_column(Text, nullable=True)

    expected_behavior: Mapped[str | None] = mapped_column(Text, nullable=True)
    actual_behavior: Mapped[str | None] = mapped_column(Text, nullable=True)

    first_seen_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    last_known_good_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    error_code: Mapped[str | None] = mapped_column(Text, nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    error_signature_norm: Mapped[str | None] = mapped_column(Text, nullable=True)

    root_cause_status: Mapped[str] = mapped_column(Text, default="UNKNOWN", server_default="UNKNOWN")
    root_cause: Mapped[str | None] = mapped_column(Text, nullable=True)
    root_cause_confidence: Mapped[Decimal | None] = mapped_column(Numeric(3, 2), nullable=True)

    workaround: Mapped[str | None] = mapped_column(Text, nullable=True)
    resolution_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    prevention_summary: Mapped[str | None] = mapped_column(Text, nullable=True)

    knowledge_quality_score: Mapped[Decimal] = mapped_column(
        Numeric(3, 2), default=0, server_default="0"
    )

    created_by: Mapped[str | None] = mapped_column(Text, nullable=True)
    assigned_to: Mapped[str | None] = mapped_column(Text, nullable=True)

    # --- provenance (migration 002) ------------------------------------
    # Where this record came from, and whether a person has touched it since.
    source_type: Mapped[str] = mapped_column(Text, default="new_kt", server_default="new_kt")
    source_ref: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_hash: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Set the moment someone edits an imported record. Re-extraction reads
    # this and refuses — a better model is still not better than a person who
    # read the ticket.
    human_reviewed: Mapped[bool] = mapped_column(
        Boolean, default=False, server_default="false")
    extractor_version: Mapped[str | None] = mapped_column(Text, nullable=True)

    metadata_: Mapped[dict] = mapped_column(
        "metadata", JSONB, default=dict, server_default="{}"
    )

    # delete-orphan throughout: a KT specification without its ticket is not
    # a record, it is a fragment nobody can interpret.
    specifications = relationship(
        "KTSpecification", back_populates="ticket",
        cascade="all, delete-orphan", passive_deletes=True,
    )
    distinctions = relationship(
        "KTDistinction", back_populates="ticket",
        cascade="all, delete-orphan", passive_deletes=True,
    )
    changes = relationship(
        "KTChange", back_populates="ticket",
        cascade="all, delete-orphan", passive_deletes=True,
    )
    hypotheses = relationship(
        "KTHypothesis", back_populates="ticket",
        cascade="all, delete-orphan", passive_deletes=True,
    )
    evidence = relationship(
        "TicketEvidence", back_populates="ticket",
        cascade="all, delete-orphan", passive_deletes=True,
    )
    tests = relationship(
        "DiagnosticTest", back_populates="ticket",
        cascade="all, delete-orphan", passive_deletes=True,
    )
    actions = relationship(
        "TicketAction", back_populates="ticket",
        cascade="all, delete-orphan", passive_deletes=True,
    )
    root_causes = relationship(
        "RootCause", back_populates="ticket",
        cascade="all, delete-orphan", passive_deletes=True,
    )
    timeline = relationship(
        "TicketTimeline", back_populates="ticket",
        cascade="all, delete-orphan", passive_deletes=True,
        order_by="TicketTimeline.occurred_at",
    )
    chunks = relationship(
        "RagChunk", back_populates="ticket",
        cascade="all, delete-orphan", passive_deletes=True,
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<SupportTicket {self.ticket_number} {self.title!r}>"


class TicketTimeline(Base):
    __tablename__ = "ticket_timeline"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.uuid_generate_v4()
    )
    ticket_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("support_tickets.id", ondelete="CASCADE")
    )

    event_type: Mapped[str] = mapped_column(Text)
    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))

    component: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str] = mapped_column(Text)
    source: Mapped[str | None] = mapped_column(String, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    ticket = relationship("SupportTicket", back_populates="timeline")
